swas.UI/Controllers/StagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using swas.BAL.DTO;
using swas.BAL.Helpers;
using swas.BAL.Interfaces;
using swas.DAL;
using swas.DAL.Models;
using System.Threading.Tasks;


namespace swas.UI.Controllers
{
    ///Created and Reviewed by : Sub Maj M Sanal
    ///Reviewed Date : 31 Jul 23
    ///Tested By :- 
    ///Tested Date : 
    ///Start
   
    public class StagesController : Controller
    {
        private readonly IStagesRepository _stagesRepository;
        private readonly ApplicationDbContext _context;
        private readonly IDataProtector _dataProtector;
        private readonly ILogger<StagesController> _logger;
        public StagesController(ApplicationDbContext context, IDataProtectionProvider DataProtector, IStagesRepository stagesRepository, ILogger<StagesController> logger)
        {
            _context = context;
            _dataProtector = DataProtector.CreateProtector("swas.UI.Controllers.UnitDtlsController");
            _stagesRepository = stagesRepository;
            _logger = logger;
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // GET: Stages
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Index()
        {
            var stages = await _stagesRepository.GetAll();
            return View(stages);
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // GET: Stages/Details/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Details(int id)
        {
            var stage = await _stagesRepository.Get(id);
            if (stage == null)
            {
                return NotFound();
            }

            return View(stage);
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // GET: Stages/Create
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Create()
        {
            var stages = await _stagesRepository.GetAll();
            return View(stages);
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // POST: Stages/Create
      
        [HttpPost]
        public async Task<IActionResult> CreateStage(tbl_mStages stage)
        {
            Login Logins = SessionHelper.GetObjectFromJson<Login>(HttpContext.Session, "User");
            try
            {
                if (ModelState.IsValid)
                {
                    stage.EditDeleteBy = (int)Logins.unitid;
                    stage.UpdatedByUserId = (int)Logins.unitid;
                    stage.IsDeleted = false;
                    stage.IsActive = true;
                    stage.DateTimeOfUpdate = DateTime.Now;
                    stage.EditDeleteDate = DateTime.Now;
                    stage.InitiaalID = false;
                    stage.FininshID = false;

                    await _stagesRepository.Add(stage);
                    return RedirectToAction(nameof(Create));
                }
                return View(stage);
            }
            catch (Exception ex)
            {
                int dynamicEventId = DateTime.UtcNow.Ticks.GetHashCode();
                var eventId = new EventId(dynamicEventId, "CreateStage");
                _logger.Log(LogLevel.Error, eventId, "An error occurred while on CreateStage in StagesController.", ex, (s, e) => $"{s} - {e?.Message}");

                return RedirectToAction("Error", "Home");
            }
           
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // GET: Stages/Edit/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var stage = await _stagesRepository.Get(id);
            if (stage == null)
            {
                return NotFound();
            }
            return View(stage);
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // POST: Stages/Edit/5
        [Authorize(Policy = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, tbl_mStages stage)
        {
            try
            {
                if (id != stage.StagesId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    await _stagesRepository.UpdateWithReturn(stage);
                    return RedirectToAction(nameof(Index));
                }

                return View(stage);
            }
            catch (Exception ex)
            {
                int dynamicEventId = DateTime.UtcNow.Ticks.GetHashCode();
                var eventId = new EventId(dynamicEventId, "Edit");
                _logger.Log(LogLevel.Error, eventId, "An error occurred while on Edit in StagesController.", ex, (s, e) => $"{s} - {e?.Message}");

                return RedirectToAction("Error", "Home");
            }
            
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // GET: Stages/Delete/5
        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var stage = await _stagesRepository.Delete(id);
            if (stage == null)
            {
                return NotFound();
            }
            return View(stage);
        }
        ///Created and Reviewed by : Sub Maj Sanal
        //Reviewed Date : 31 Jul 23
        // POST: Stages/Delete/5
        [Authorize(Policy = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _stagesRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                int dynamicEventId = DateTime.UtcNow.Ticks.GetHashCode();
                var eventId = new EventId(dynamicEventId, "DeleteConfirmed");
                _logger.Log(LogLevel.Error, eventId, "An error occurred while on DeleteConfirmed in StagesController.", ex, (s, e) => $"{s} - {e?.Message}");
                return RedirectToAction("Error", "Home");
            }
         
        }
    }

}

swas.UI/Controllers/StatusController.cs
using Grpc.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using swas.BAL.DTO;
using swas.BAL.Helpers;
using swas.BAL.Interfaces;
using swas.BAL.Repository;
using swas.DAL;
using swas.DAL.Models;
using System.Threading.Tasks;

namespace swas.UI.Controllers
{

    public class StatusController : Controller
    {
        private readonly IStatusRepository _statusRepository;
        private readonly ApplicationDbContext _context;
        private readonly IDataProtector _dataProtector;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILogger<StatusController> _logger;
        public StatusController( ApplicationDbContext context, IDataProtectionProvider DataProtector , IStatusRepository statusRepository, IHttpContextAccessor httpContextAccessor, ILogger<StatusController> logger)
        {
            
            _context = context;
            _dataProtector = DataProtector.CreateProtector("swas.UI.Controllers.UnitDtlsController");
            _statusRepository = statusRepository;
            _httpContextAccessor = httpContextAccessor;
            _logger = logger;

        }

        [Authorize(Policy = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {

            var ipAddress = HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString();
            var currentDatetime = DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss");
            var watermarkText = $" {ipAddress}\n  {currentDatetime}";

            TempData["ipadd"] = watermarkText;

            var status = await _statusRepository.GetAll();
            return View(status);
        }


        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Details(int id)
        {
            var status = await _statusRepository.Get(id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

     

        //[Authorize(Policy = "Admin")]
        //public async Task<IActionResult> Create()
        //{
        //    var Status = await _statusRepository.GetAll();
        //    return View(Status);
            
        //}


        
        //[HttpPost]
        
        //public async Task<IActionResult> CreateStatus (tbl_mStatus status)
        //{
        //    Login Logins = SessionHelper.GetObjectFromJson<Login>(HttpContext.Session, "User");
        //    if (ModelState.IsValid)
        //    {
        //        status.EditDeleteBy = (int)Logins.unitid;
        //        status.UpdatedByUserId = (int)Logins.unitid;
        //        status.IsDeleted = false;
        //        status.IsActive = true;
        //        status.DateTimeOfUpdate = DateTime.Now;
        //        status.EditDeleteDate = DateTime.Now;
        //        status.InitiaalID = false;
        //        status.FininshID = false;

        //        await _statusRepository.Add(status);
        //        return RedirectToAction(nameof(Create));
        //    }
        //    //return View(status);
        //    return RedirectToAction(nameof(Create));
        //}

        [HttpPost]
        public async Task<IActionResult> Create(tbl_mStatus model)
        {
            Login Logins = SessionHelper.GetObjectFromJson<Login>(_httpContextAccessor.HttpContext.Session, "User");
            try
            {
                if (ModelState.IsValid)
                {
                    model.Status = model.Status;
                    model.IsDeleted = false;
                    model.IsActive = true;
                    model.UpdatedByUserId = (int)Logins.unitid;
                    model.DateTimeOfUpdate = DateTime.Now;
                    model.EditDeleteDate = DateTime.Now;
                    model.EditDeleteBy = (int)Logins.unitid;

                    model.InitiaalID = false;
                    model.FininshID = false;

                    if (model.StatusId == 0)
                    {
                        await _statusRepository.AddWithReturn(model);
                        //await _actionsRepository.AddWithReturn(model);
                        return Json(nmum.Save);
                    }

                    else
                    {
                        await _statusRepository.UpdateWithReturn(model);
                        return Json(nmum.Update);
                    }
                }
                else
                {
                    return Json(nmum.NotSave);
                }
            }
            catch (Exception ex)
            {
                int dynamicEventId = DateTime.UtcNow.Ticks.GetHashCode();
                var eventId = new EventId(dynamicEventId, "Create");
                _logger.Log(LogLevel.Error, eventId, "An error occurred while on Create in StatusController.", ex, (s, e) => $"{s} - {e?.Message}");

                return RedirectToAction("Error", "Home");
            }
        }


        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var status = await _statusRepository.Get(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }


        [Authorize(Policy = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
     
        public async Task<IActionResult> Edit(int id, tbl_mStatus status)
        {
            try
            {
                if (id != status.StatusId)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    await _statusRepository.UpdateWithReturn(status);
                    return RedirectToAction(nameof(Index));
                }

                //return View(status);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                int dynamicEventId = DateTime.UtcNow.Ticks.GetHashCode();
                var eventId = new EventId(dynamicEventId, "Edit");
                _logger.Log(LogLevel.Error, eventId, "An error occurred while on Edit in StatusController.", ex, (s, e) => $"{s} - {e?.Message}");

                return RedirectToAction("Error", "Home");
            }
            
        }


        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _statusRepository.Delete(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }

        

        [Authorize(Policy = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _statusRepository.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                int dynamicEventId = DateTime.UtcNow.Ticks.GetHashCode();
                var eventId = new EventId(dynamicEventId, "DeleteConfirmed");
                _logger.Log(LogLevel.Error, eventId, "An error occurred while on DeleteConfirmed in StatusController.", ex, (s, e) => $"{s} - {e?.Message}");

                return RedirectToAction("Error", "Home");
            }
           
        }

        
    }

}

swas.UI/Views/Status/Create.cshtml
@*View Created by Sub Maj M Sanal Kumar on :  02 Aug 23
Reviewd by Hav Mani on :
*@

@using swas.DAL.Models
@model List<tbl_mStatus>

@{
    ViewBag.Title = "Sub Stages List";
}



<style>
    .underline-h5 {
        padding: 0.5rem;
        width: 100%;
        margin: -16px auto; /* Center the box */
        text-align: center;
        border-color: #03c1fc;
        /*box-shadow: 2px 6px 5px -3px #062b50;*/
        background-color: #0cafff;
        color: white;
        font-family: Arial;
        font-size: 15px;
        margin-bottom: 0.5rem;
        height: -1px;
    }
</style>
<button type="button" id="AddButon" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#SubStageAdd" style="margin-left: 91%;">
    Add New Sub Stage
</button>
@*<button id="addNewButton" class="btn btn-primary"><a href="/Actions/Create">Add New</a></button>*@

<div class="card radius-10 w-100">
    <div class="card-body">

        <table id="SoftwareType" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Sub Stage ID</th>
                    <th>Sub Stage</th>
                    <th>Is Active</th>
                    <th>Edit/Delete By</th>
                    <th>Edit/Delete Date</th>
                    <th>Updated By User ID</th>
                    <th>Date of Update</th>
                    @*<th>Delete</th>*@

                </tr>
            </thead>
            <tbody>
                @foreach (var Substage in Model)
                {
                    if (Substage.IsActive == true)
                    {
                        <tr>
                            <td>@Substage.StatusId</td>
                            <td>@Substage.Status</td>
                            <td>@Substage.IsActive</td>
                            <td>@Substage.EditDeleteBy</td>
                            <td>@Substage.EditDeleteDate?.ToString("dd-MM-yyyy")</td>
                            <td>@Substage.UpdatedByUserId</td>
                            <td>@Substage.DateTimeOfUpdate?.ToString("dd-MM-yyyy")</td>
                            @*  <td>
                    <a asp-action="EditStage" asp-route-id="@stage.StagesId" class="btn btn-secondary btn-ecomm"><i class='bx bx-edit'></i></a>
                    <a data-id="@stage.StagesId" data-url="@Url.Action("Create", "Stages")" class="btn btn-secondary btn-ecomm delete-btn"><i class='bx bx-trash'></i></a>
                    </td>*@

                        </tr>
                    }

                }
            </tbody>
        </table>

    </div>
</div>

<div class="modal fade" id="SubStageAdd" tabindex="-1" aria-labelledby="ProjectAddLabel" aria-hidden="true">
    <div class="modal-dialog" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                @* <h5 class="modal-title" id="UnitAddLabel">Add Action</h5>*@
                <h5 class="text-center mb-4 underline-h5" style="text-align: center; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); position: relative;height: 33px;">
                    <span>
                        New Sub Stage Page
                    </span>
                </h5>
            </div>
            <div class="modal-body">

                @Html.Partial("_CreateStatus", new tbl_mStatus())


            </div>

        </div>
    </div>
</div>


<script src="~/developerjs/stage.js"></script>

<script src="~/developerjs/status.js"></script>

swas.UI/Views/Status/Edit.cshtml
@*@model swas.DAL.Models.tbl_mStatus

@{
    ViewData["Title"] = "Edit Stage";

}

<div>
    <div class="container mt-1">
        <div class="row justify-content-center">
            <div class="container-fluid">
                <form asp-action="Edit" asp-controller="Status" method="post">
                    <input type="hidden" asp-for="StatusId" />
                    <div class="row">
                
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Status"><b>Status Name</b> <span class="required-indicator"><font style="color:red;"><b>*</b></font></span></label>
                                <input asp-for="Status" class="form-control" required onkeyup="ValInData(this)" value="@Model.Status" />
                                <span asp-validation-for="Status" class="text-danger"></span>
                                <div class="invalid-feedback">Please provide a Status name.</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Statseq"><b>StatSeq</b> <span class="required-indicator"><font style="color:red;"><b>*</b></font></span></label>
                            <input asp-for="Statseq" class="form-control" id="statseq" required onkeyup="ValInData(this)" value="@Model.Statseq" />
                            <div class="invalid-feedback">Please provide the Status Seq </div>
                            <span asp-validation-for="Statseq" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="text-center" style="margin-top: 2rem;">

                            <button type="submit" data-id="@Model.StatusId" data-name="@Model.Status" class="btn btn-primary btnupdate" style="margin-top:1rem;">Update</button>

                            <button class="btn btn-secondary" type="button" style="margin-top: 1rem;">
                                <a href="/Status/Index" style="color: white;">Close</a>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {

    <partial name="_ValidationScriptsPartial" />
}

    <script src="~/developerjs/stage.js"></script>*@


@model swas.DAL.Models.tbl_mStatus

@{
    ViewData["Title"] = "Edit Sub Stage";

}

<div>
    <div class="container mt-1">
        <div class="row justify-content-center">
            <div class="container-fluid">
                <form asp-action="Edit" asp-controller="Stauts" method="post">
                    <input type="hidden" asp-for="StatusId" />
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Status"><b>Stage Name</b> <span class="required-indicator"><font style="color:red;"><b>*</b></font></span></label>
                                <input asp-for="Status" class="form-control" required onkeyup="ValInData(this)" value="@Model.Status" />
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="text-center" style="margin-top: 2rem;">

                            <button type="submit" data-id="@Model.StatusId" data-name="@Model.Status" class="btn btn-primary btnupdate" style="margin-top:1rem;">Update</button>

                            <button class="btn btn-secondary" type="button" style="margin-top: 1rem;">
                                <a href="/Status/Create" style="color: white;">Close</a>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {

    <partial name="_ValidationScriptsPartial" />
}




    <script src="~/developerjs/Status.js"></script>

swas.UI/Views/Status/Index.cshtml
@*@using swas.DAL.Models
@model List<tbl_mStatus>

@{
    ViewBag.Title = "Status List";
}

<style>
    .underline-h5 {
        padding: 0.5rem;
        width: 100%;
        margin: -16px auto; /* Center the box */
        text-align: center;
        border-color: #03c1fc;
        /*box-shadow: 2px 6px 5px -3px #062b50;*/
        background-color: #0cafff;
        color: white;
        font-family: Arial;
        font-size: 15px;
        margin-bottom: 0.5rem;
        height: -1px;
    }
</style>
<button type="button" id="AddButon" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#UnitAdd" style="margin-left: 91%;">
    Add New Status
</button>
*@
@*<div class="card radius-10 w-100">
    <div class="card-body">

        <table id="SoftwareType" class="table table-striped table-bordered">
            <!-- Table header -->
            <thead>
                <tr>
                    <th>Ser No</th>
                    <th>Stage Id</th>
                    <th>Status</th>
                    <th>User Id</th>
                    <th>Edit/Delete Date</th>
                    <th>Statseq</th>
                    <th>Delete</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var models in Model)
                {
                    <tr>
                        <td>@(Model.IndexOf(models) + 1)</td>
                        <td>@models.StageId</td>
                        <td>@models.Status</td>
                        <td>@models.UpdatedByUserId</td>
                        <td>@models.DateTimeOfUpdate?.ToString("dd-MM-yyyy")</td>
                        <td>@models.Statseq</td>
                        @*<td>@models.ActionSeq</td>*@
                       @* <td>

                            <a asp-action="Edit" asp-route-id="@models.StatusId" class="btn btn-secondary btn-ecomm"><i class='bx bx-edit'></i></a>


                            <a data-id="@models.StatusId" data-url="@Url.Action("Delete", "Status")" class="btn btn-secondary btn-ecomm delete-btn"><i class='bx bx-trash'></i></a>

                        </td>
                    </tr>

                }

            </tbody>

        </table>

    </div>
</div>







<script src="~/js/sweetalert2.all.min.js"></script>


<div class="modal fade" id="UnitAdd" tabindex="-1" aria-labelledby="ProjectAddLabel" aria-hidden="true">
    <div class="modal-dialog" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
               
                <h5 class="text-center mb-4 underline-h5" style="text-align: center; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5); position: relative;height: 33px;">
                    <span>
                        New Status Page
                    </span>
                </h5>
            </div>
            <div class="modal-body">

                @Html.Partial("_CreateStatus", new tbl_mStatus())


            </div>

        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }


<script src="~/developerjs/status.js"></script>

*@


@using swas.BAL.DTO
@using swas.DAL.Models
@model List<tbl_mStatus>

@{
    ViewBag.Title = "Sub Stage List";
}

<style>
         .underline-h5 {
            padding: 0.5rem;
            width: 100%;
            margin: -16px auto; /* Center the box */
            text-align: center;
            border-color: #03c1fc;
            /*box-shadow: 2px 6px 5px -3px #062b50;*/
            background-color: #0cafff;
            color: white;
            font-family: Arial;
            font-size: 15px;
            margin-bottom: 0.5rem;
            height: -1px;
        }
    </style>

<button type="button" class="btn btn-success btn-Mapping">Add Sub Stage</button>

<div class="card radius-10 w-100">
    <div class="card-body">
      

        <table id="SoftwareType" class="table table-striped table-bordered">
            <!-- Table header -->
            <thead>
                <tr>
                    <th>Ser No</th>
                    <th>Sub Stage ID</th>
                    <th>Sub Stage</th>
                    <th>Is Active</th>
                    <th>Edit/Delete By</th>
                    <th>Edit/Delete Date</th>
                    <th>Updated By User ID</th>
                    <th>Date of Update</th>

                    <th>Edit/Delete</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var models in Model)
                {
                    
                    <tr>
                        <td>@(Model.IndexOf(models) + 1)</td>
                        <td id="spnStatusId">@models.StatusId</td>
                        <td id="StatusNames">@models.Status</td>
                        <td>@models.IsActive</td>
                        <td>@models.EditDeleteBy</td>
                        <td>@models.EditDeleteDate?.ToString("dd-MM-yyyy")</td>
                        <td>@models.UpdatedByUserId</td>
                        <td>@models.DateTimeOfUpdate?.ToString("dd-MM-yyyy")</td>
                        

                        
                        <td>
                           
                            <a class="btn btn-secondary btn-edit"><i class='bx bx-edit'></i></a>


                            <a onclick="functionConfirm1('@models.StatusId')" class="btn btn-secondary btn-delete"><i class="bx bx-trash"></i></a>

                        </td>
                    
                    </tr>

                }

            </tbody>

        </table>
      
    </div>
</div>







<script src="~/js/sweetalert2.all.min.js"></script>

<div class="modal fade" id="unitMapping" tabindex="-1" role="dialog" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="modal-header"><h5 class="card-title Fwdtitle">New Sub Stage Details</h5></div>
                            <div class="card-body">
                                <input hidden class="form-control" type="text" id="ActionsId" name="ActionsId" value="0">
                                <div class="form-row">
                                    <div class="form-group col-md-6 ProjectsFwd">
                                        <label for="StatusNames">Sub Stage</label>
                                        <input class="form-control" type="text" id="StatusNames" name="StatusNames">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="StatusId">Status ID</label>
                                        <input class="form-control" type="text" id="StatusId" name="StatusId">
                                    </div>
                                    <div class="form-group col-md-12">
                                        <button class="btn btn-submit" type="button" id="btnsave" style="margin-left: 20rem; background-color: #2d5eff; color: white;">
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>


               


            </div>
        </div>
    </div>
</div>


<script src="~/DeveloperJs/SubStage.js"></script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }